export TERM=xterm-256color-italic
export TZ=Europe/Berlin

export EDITOR=vim
export VISUAL=vim

export DOTFILES="$HOME/dotfiles"

# adding path directory for custom scripts
export PATH="$PATH:$DOTFILES/bin"
export PATH="$PATH:$HOME/.rvm/bin"
export PATH="$PATH:$HOME/.cargo/bin"

alias zshrc="vim $HOME/.zshrc"
alias prezto="vim $HOME/.zpreztorc"
alias reload="source $HOME/.zshrc"

ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="dd.mm.yyyy"

export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'

[ -f $HOME/.zprezto/init.zsh ] && source $HOME/.zprezto/init.zsh
[ -f $HOME/.nvm/nvm.sh ] && source $HOME/.nvm/nvm.sh
[ -f $HOME/.rvm/scripts/rvm ] && source $HOME/.rvm/scripts/rvm

export CDPATH=".:$HOME:$DOTFILES:$HOME/github:$HOME/svn:$HOME/dropbox"

prompt agnoster
prompt_context() {}

# [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
