export TERM=xterm-256color-italic
export TZ=Europe/Berlin

export EDITOR=vim
export VISUAL=vim

export DOTFILES="$HOME/dotfiles"
export JAVA_HOME="/usr/lib/jvm/java-8-oracle"
export CATALINA_HOME="$HOME/tomcat"

# adding path directory for custom scripts
export PATH="$PATH:$DOTFILES/bin"
export PATH="$PATH:$HOME/.rvm/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.miniconda/bin"
export PATH="$PATH:$JAVA_HOME/bin"
export PATH="$PATH:$CATALINA_HOME/bin"

alias vi="vim"
alias zshrc="vim $HOME/.zshrc"
alias prezto="vim $HOME/.zpreztorc"
alias vimrc="vim $HOME/.vim/vimrc"
alias reload="source $HOME/.zshrc"
alias mvni="mvn clean install -DskipTests"
alias tstart="$CATALINA_HOME/bin/startup.sh"
alias tstop="$CATALINA_HOME/bin/shutdown.sh"
alias notebook="ipython notebook --port 3000 --ip 0.0.0.0"

ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="dd.mm.yyyy"

# enable npm completion
source <(npm completion)

/usr/bin/keychain "$HOME/.ssh/id_rsa"
source "$HOME/.keychain/$HOST-sh"

export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'

[ -f $HOME/.zprezto/init.zsh ] && source $HOME/.zprezto/init.zsh
[ -f $HOME/.nvm/nvm.sh ] && source $HOME/.nvm/nvm.sh
[ -f $HOME/.rvm/scripts/rvm ] && source $HOME/.rvm/scripts/rvm
[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh

export CDPATH=".:$HOME:$DOTFILES:$HOME/github:$HOME/shared_github:$HOME/svn:$HOME/dropbox:$HOME/tomcat"

prompt agnoster
prompt_context() {}
