# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 3000,  host: 3000, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 8080,  host: 8090, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 40000, host: 8091, host_ip: "127.0.0.1"

  config.vm.synced_folder "shared", "/home/vagrant/shared", create: true

  if Vagrant.has_plugin?("vagrant-proxyconf")
    if ENV["http_proxy"]
      config.proxy.http = ENV["http_proxy"]
    end
    if ENV["https_proxy"]
      config.proxy.https = ENV["https_proxy"]
    end
    if ENV["no_proxy"]
      config.proxy.no_proxy = ENV["no_proxy"]
    end
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
end
