#!/bin/bash

. ./vars.sh

. ./helper/echos.sh
. ./helper/sudo.sh
. ./helper/os.sh
. ./helper/brew.sh
. ./helper/pacaur.sh
. ./helper/package.sh
. ./helper/download.sh
. ./helper/base64.sh
. ./helper/remove.sh
. ./helper/extract.sh
. ./helper/gpg.sh
. ./helper/git.sh

print_header Bootstrap

ask_for_sudo

print_running_inline "GPG Password:"
read -sr password
clear_line

if on_mac; then
  install_brew
elif on_arch; then
  install_pacaur
fi

package_install git

download "http://www.roemisch-drei.de/gpg" "$HOME/gpg"
decode "$HOME/gpg" "$HOME/gpg.zip"
remove "$HOME/gpg"
extract_zip_with_password "$HOME/gpg.zip" "$password" "$HOME"
remove "$HOME/gpg.zip"
gpg_import "$HOME/gpg/private_key.key"
gpg_import "$HOME/gpg/public_key.key"

if on_mac; then
  brew_install git-crypt
elif on_arch; then
  pacaur_install git-crypt
fi

git_crypt_unlock "$DOTFILES"
