#!/bin/sh

./helper/os.sh
./helper/brew.sh
./helper/pacaur.sh
./helper/package.sh
./helper/download.sh
./helper/base64.sh
./helper/remove.sh
./helper/extract.sh
./helper/gpg.sh
./helper/git.sh

password=

if on_mac; then
  brew_install
elif on_arch; then
  pacaur_install
fi

package_install git

download "http://www.roemisch-drei.de/gpg" "$HOME/gpg"
decode "$HOME/gpg" "$HOME/gpg.zip"
remove "$HOME/gpg"
extract_zip_with_password "$HOME/gpg.zip" "$HOME/gpg" "$password"
remove "$HOME/gpg.zip"
gpg_import "$HOME/gpg/private_key.key"
gpg_import "$HOME/gpg/public_key.key"
remove "$HOME/gpg"

git_crypt_unlock "$DOTFILES"
