#!/bin/bash

. ./helper/echos.sh
. ./helper/defaults.sh

print_header "Dock"

defaults_enable com.apple.dock autohide  # Autohide dock.
defaults_set_int com.apple.dock tilesize 64  # Set dock icon size.
defaults_enable com.apple.dock magnification  # Enable dock magnification.
defaults_set_int com.apple.dock largesize 96  # Set dock magnificated icon size.
killall Dock
defaults_set NSGlobalDomain AppleInterfaceStyle Dark  # Use dark menu bar and dock.

print_header "Keyboard"

defaults_set_int NSGlobalDomain KeyRepeat 1  # Set blazingly fast key repeat rate.
defaults_set_int NSGlobalDomain InitialKeyRepeat 10  # Set blazingly fast initial key repeat rate.

print_header "Finder"

defaults_enable com.apple.finder AppleShowAllFiles  # Show hidden files.
defaults_enable NSGlobalDomain AppleShowAllExtensions  # Show all file extensions.
defaults_disable com.apple.finder FXEnableExtensionsChangeWarning  # Disable file extension change warning.
defaults_enable com.apple.finder ShowStatusBar  # Show status bar.
defaults_enable com.apple.finder ShowPathBar  # Show path bar.
defaults_disable com.apple.finder ShowRecentTags  # Hide tags in sidebar.
defaults_enable com.apple.finder QuitMenuItem  # Allow quitting finder via ⌘ + Q.
defaults_set_int com.apple.finder SidebarWidth 175  # Greater sidebar width.
defaults_disable com.apple.finder WarnOnEmptyTrash  # No warning before emptying trash.
# Set search scope.
# This Mac       : `SCev`
# Current Folder : `SCcf`
# Previous Scope : `SCsp`
defaults_set com.apple.finder FXDefaultSearchScope SCcf
# Set preferred view style.
# Icon View   : `icnv`
# List View   : `Nlsv`
# Column View : `clmv`
# Cover Flow  : `Flwv`
defaults_set com.apple.finder FXPreferredViewStyle clmv
rm -rf ~/.DS_Store
# Set default path for new windows.
# Computer     : `PfCm`
# Volume       : `PfVo`
# $HOME        : `PfHm`
# Desktop      : `PfDe`
# Documents    : `PfDo`
# All My Files : `PfAF`
# Other…       : `PfLo`
defaults_set com.apple.finder NewWindowTarget PfHm
killall Finder
