#!/bin/bash

. ./helper/sudo.sh
. ./helper/brew.sh
. ./helper/python.sh
. ./helper/cmd.sh
. ./helper/npm.sh
. ./helper/ruby.sh

ask_for_sudo

brew_install neovim

brew_cask_install miniconda
PATH=/usr/local/miniconda3/bin:$PATH  # Activate miniconda environment
pip_install neovim
eval_cmd "Install system pip" "sudo /usr/bin/easy_install pip"
eval_cmd "Install system neovim" "sudo /usr/local/bin/pip install neovim"

brew_install node
npm_install neovim

gem_install neovim
