API_VERSION = "2"

SCRIPTS = "~/dotfiles/vagrant/scripts"

Vagrant.configure(API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.ssh.insert_key = false

  if Vagrant.has_plugin?("vagrant-proxyconf")
    if ENV["http_proxy"]
      config.proxy.http = ENV["http_proxy"]
    end
    if ENV["https_proxy"]
      config.proxy.https = ENV["https_proxy"]
    end
    if ENV["no_proxy"]
      config.proxy.no_proxy = ENV["no_proxy"]
    end
  end

  # synced folders
  config.vm.synced_folder "~/dotfiles", "/home/vagrant/dotfiles"
  config.vm.synced_folder "github",     "/home/vagrant/github", create: true
  config.vm.synced_folder "svn",        "/home/vagrant/svn",    create: true
  config.vm.synced_folder "shared",     "/home/vagrant/shared", create: true

  # provision scripts
  config.vm.provision :shell, privileged: false, :path => "#{SCRIPTS}/base.sh"
  config.vm.provision :shell, privileged: false, :path => "#{SCRIPTS}/git.sh"
  config.vm.provision :shell, privileged: false, :path => "#{SCRIPTS}/shell.sh"
  config.vm.provision :shell, privileged: false, :path => "#{SCRIPTS}/node.sh"
  config.vm.provision :shell, privileged: false, :path => "#{SCRIPTS}/tmux.sh"
  config.vm.provision :shell, privileged: false, :path => "#{SCRIPTS}/neovim.sh"
end
