API_VERSION = "2"

SCRIPTS = "~/dotfiles/vagrant/scripts"

Vagrant.configure(API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.ssh.insert_key = false

  if Vagrant.has_plugin?("vagrant-proxyconf")
    if ENV["http_proxy"]
      config.proxy.http = ENV["http_proxy"]
    end
    if ENV["https_proxy"]
      config.proxy.https = ENV["https_proxy"]
    end
    if ENV["no_proxy"]
      config.proxy.no_proxy = ENV["no_proxy"]
    end
  end

  # give vm 1/4 system memory
  config.vm.provider "virtualbox" do |v|
    host = RbConfig::CONFIG['host_os']

    if host =~ /darwin/
      mem = `sysctl -n hw.memsize`.to_i / 1024
    elsif host =~ /linux/
      mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kb//'`.to_i
    elsif host =~ /mswin|mingw|cygwin/
      mem = `wmic computersystem Get TotalPhysicalMemory`.split[1].to_i / 1024
    end

    mem = mem / 1024 / 4
    v.customize ["modifyvm", :id, "--memory", mem]
  end

  # synced folders
  config.vm.synced_folder "~/dotfiles", "/home/vagrant/dotfiles", nfs: true
  config.vm.synced_folder "github",     "/home/vagrant/github",   nfs: true, create: true
  config.vm.synced_folder "svn",        "/home/vagrant/svn",      nfs: true, create: true
  config.vm.synced_folder "shared",     "/home/vagrant/shared",   nfs: true, create: true

  # provision scripts
  config.vm.provision :shell, privileged: false, :path => "#{SCRIPTS}/base.sh"
  config.vm.provision :shell, privileged: false, :path => "#{SCRIPTS}/git.sh"
  config.vm.provision :shell, privileged: false, :path => "#{SCRIPTS}/shell.sh"
  config.vm.provision :shell, privileged: false, :path => "#{SCRIPTS}/node.sh"
  config.vm.provision :shell, privileged: false, :path => "#{SCRIPTS}/tmux.sh"
  config.vm.provision :shell, privileged: false, :path => "#{SCRIPTS}/neovim.sh"
  # config.vm.provision :shell, privileged: false, :path => "#{SCRIPTS}/latex.sh"
end
