HOST = RbConfig::CONFIG['host_os']
API_VERSION = "2"

USERNAME= "Fey"
MAC_SCRIPTS = "~/dotfiles/vagrant/scripts"
WIN_SCRIPTS = "C:\\Users\\#{USERNAME}\\dotfiles\\vagrant\\scripts"

Vagrant.configure(API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.ssh.insert_key = false

  # configure proxy if necassary
  if Vagrant.has_plugin?("vagrant-proxyconf")
    if ENV["http_proxy"]
      config.proxy.http = ENV["http_proxy"]
    end
    if ENV["https_proxy"]
      config.proxy.https = ENV["https_proxy"]
    end
    if ENV["no_proxy"]
      config.proxy.no_proxy = ENV["no_proxy"]
    end
  end

  # give vm 1/4 system memory
  config.vm.provider "virtualbox" do |v|
    if HOST =~ /darwin/
      mem = `sysctl -n hw.memsize`.to_i / 1024
    elsif HOST =~ /linux/
      mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kb//'`.to_i
    elsif HOST =~ /mswin|mingw|cygwin/
      mem = `wmic computersystem Get TotalPhysicalMemory`.split[1].to_i / 1024
    end

    mem = mem / 1024 / 4
    v.customize ["modifyvm", :id, "--memory", mem]
  end

  if HOST =~ /mswin|mingw|cygwin/
    # synced folders
    config.vm.synced_folder "C:\\Users\\Fey\\dotfiles",     "/home/vagrant/dotfiles"
    config.vm.synced_folder "C:\\Users\\Fey\\home\\svn",    "/home/vagrant/svn"
    config.vm.synced_folder "C:\\Users\\Fey\\home\\github", "/home/vagrant/github"

    # provision scripts
    config.vm.provision :shell, privileged: false, :path => "#{WIN_SCRIPTS}\\base.sh"
    config.vm.provision :shell, privileged: false, :path => "#{WIN_SCRIPTS}\\git.sh"
    config.vm.provision :shell, privileged: false, :path => "#{WIN_SCRIPTS}\\shell.sh"
    config.vm.provision :shell, privileged: false, :path => "#{WIN_SCRIPTS}\\node.sh"
    config.vm.provision :shell, privileged: false, :path => "#{WIN_SCRIPTS}\\vim.sh"
    config.vm.provision :shell, privileged: false, :path => "#{WIN_SCRIPTS}\\tmux.sh"
  else
    # synced folders
    config.vm.synced_folder "~/dotfiles", "/home/vagrant/dotfiles"
    config.vm.synced_folder "~/Dropbox",  "/home/vagrant/dropbox"
    config.vm.synced_folder "github",     "/home/vagrant/github",   create: true

    # provision scripts
    config.vm.provision :shell, privileged: false, :path => "#{MAC_SCRIPTS}/base.sh"
    config.vm.provision :shell, privileged: false, :path => "#{MAC_SCRIPTS}/git.sh"
    config.vm.provision :shell, privileged: false, :path => "#{MAC_SCRIPTS}/shell.sh"
    config.vm.provision :shell, privileged: false, :path => "#{MAC_SCRIPTS}/node.sh"
    config.vm.provision :shell, privileged: false, :path => "#{MAC_SCRIPTS}/vim.sh"
    config.vm.provision :shell, privileged: false, :path => "#{MAC_SCRIPTS}/tmux.sh"
    config.vm.provision :shell, privileged: false, :path => "#{MAC_SCRIPTS}/tensorflow.sh"
    config.vm.provision :shell, privileged: false, :path => "#{MAC_SCRIPTS}/latex.sh"
  end

end
