export EDITOR=vim
export EDITOR=vim

alias vi=nvim
alias vim=nvim
alias zshrc="vim ~/dotfiles/macos/zshrc"
alias reload="source ~/.zshrc"

export DOTFILES=~/dotfiles
export GITHUB=~/github

ENABLE_CORRECTION="true"

export PATH="$PATH:$DOTFILES/bin"

export CDPATH=".:$HOME:$GITHUB:$DOTFILES"

# NPM Autocompletion
source <(npm completion)

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
