#!/bin/bash

. ./vars.sh

. ./helper/echos.sh
. ./helper/apt.sh
. ./helper/cmd.sh
. ./helper/download.sh
. ./helper/remove.sh
. ./helper/python.sh

print_header Cuda

apt_purge "nvidia*"
apt_add_ppa ppa:graphics-drivers/ppa
apt_install nvidia-381

download "http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_9.0.176-1_amd64.deb" "$HOME/cuda.deb"
eval_cmd "Install cuda.deb" "sudo dpkg -i $HOME/cuda.deb"
remove "$HOME/cuda.deb"
eval_cmd "Fetch cuda key" "sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub"
apt_update_sources
apt_install cuda

python_virtualenv_activate "$PYTHON_VENV/$PYTHON_VERSION"
pip_install tensorflow-gpu
