#!/bin/sh

="#[fg=colour15,bg=colour00,nobold]"
day_color="#[fg=colour11,bg=colour00,nobold]"
month_color="#[fg=colour05,bg=colour00,nobold]"
hour_color="#[fg=colour03,bg=colour00,nobold]"
minute_color="#[fg=colour01,bg=colour00,nobold]"
second_color="#[fg=colour06,bg=colour00,nobold]"

date +$day_color%d.$month_color%m.\ $hour_color%H:$minute_color%M:$second_color%S
