export TERM=linux

# adding path directory for custom scripts
export PATH=$HOME/dotfiles/bin:$PATH

alias zshrc="vim $HOME/.zshrc"
alias prezto="vim $HOME/.zpreztorc"
alias reload="source $HOME/.zshrc"
# alias vim="nvim"

ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="dd.mm.yyyy"

export NVM_DIR="$HOME/.apps/nvm"
[ -f "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh
[ -f $HOME/.zprezto/init.zsh ] && source $HOME/.zprezto/init.zsh


prompt agnoster
prompt_context() {}

